/* Generated by :claw at 2023-09-15T13:13:46.063156Z */

#if defined(__cplusplus)
#include <new>
#endif



#include "bodge_nuklear.h"

#if !defined(__CLAW_API)
#  if defined(_WIN32)
#    define __CLAW_API __declspec(dllexport)
#  elif defined(__GNUC__)
#    define __CLAW_API __attribute__((visibility("default")))
#  else
#    define __CLAW_API
#  endif
#endif

#if defined(__cplusplus)
extern "C" {
#endif


__CLAW_API void __claw_nk_window_set_size(struct nk_context* arg0, const char* name, struct nk_vec2* arg2) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:1892:13
nk_window_set_size(arg0, name, *arg2);
}

__CLAW_API void __claw_nk_window_set_position(struct nk_context* arg0, const char* name, struct nk_vec2* pos) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:1879:13
nk_window_set_position(arg0, name, *pos);
}

__CLAW_API void __claw_nk_window_set_bounds(struct nk_context* arg0, const char* name, struct nk_rect* bounds) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:1866:13
nk_window_set_bounds(arg0, name, *bounds);
}

__CLAW_API struct nk_vec2* __claw_cE3AE40FE40nk_window_get_size(struct nk_vec2* __claw_result_, const struct nk_context* arg0) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:1578:23
(*__claw_result_) = nk_window_get_size(arg0);
return __claw_result_;
}

__CLAW_API struct nk_vec2* __claw_nk_window_get_position(struct nk_vec2* __claw_result_, const struct nk_context* ctx) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:1562:23
(*__claw_result_) = nk_window_get_position(ctx);
return __claw_result_;
}

__CLAW_API struct nk_vec2* __claw_cE3AE40FE40nk_window_get_content_region_size(struct nk_vec2* __claw_result_, struct nk_context* arg0) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:1703:23
(*__claw_result_) = nk_window_get_content_region_size(arg0);
return __claw_result_;
}

__CLAW_API struct nk_vec2* __claw_cE3AE40FE40nk_window_get_content_region_min(struct nk_vec2* __claw_result_, struct nk_context* arg0) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:1666:23
(*__claw_result_) = nk_window_get_content_region_min(arg0);
return __claw_result_;
}

__CLAW_API struct nk_vec2* __claw_cE3AE40FE40nk_window_get_content_region_max(struct nk_vec2* __claw_result_, struct nk_context* arg0) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:1685:23
(*__claw_result_) = nk_window_get_content_region_max(arg0);
return __claw_result_;
}

__CLAW_API struct nk_rect* __claw_cE3AE40FE40nk_window_get_content_region(struct nk_rect* __claw_result_, struct nk_context* arg0) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:1647:23
(*__claw_result_) = nk_window_get_content_region(arg0);
return __claw_result_;
}

__CLAW_API struct nk_rect* __claw_nk_window_get_bounds(struct nk_rect* __claw_result_, const struct nk_context* ctx) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:1546:23
(*__claw_result_) = nk_window_get_bounds(ctx);
return __claw_result_;
}

__CLAW_API struct nk_vec2* __claw_cE3AE40FE40nk_widget_size(struct nk_vec2* __claw_result_, struct nk_context* arg0) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3060:23
(*__claw_result_) = nk_widget_size(arg0);
return __claw_result_;
}

__CLAW_API struct nk_vec2* __claw_cE3AE40FE40nk_widget_position(struct nk_vec2* __claw_result_, struct nk_context* arg0) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3059:23
(*__claw_result_) = nk_widget_position(arg0);
return __claw_result_;
}

__CLAW_API enum nk_widget_layout_states __claw_cE3AE40FE40nk_widget_fitting(struct nk_rect* arg0, struct nk_context* arg1, struct nk_vec2* arg2) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3057:37
return nk_widget_fitting(arg0, arg1, *arg2);
}

__CLAW_API struct nk_rect* __claw_cE3AE40FE40nk_widget_bounds(struct nk_rect* __claw_result_, struct nk_context* arg0) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3058:23
(*__claw_result_) = nk_widget_bounds(arg0);
return __claw_result_;
}

__CLAW_API struct nk_vec2* __claw_nk_vec2v(struct nk_vec2* __claw_result_, const float* xy) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3712:23
(*__claw_result_) = nk_vec2v(xy);
return __claw_result_;
}

__CLAW_API struct nk_vec2* __claw_nk_vec2iv(struct nk_vec2* __claw_result_, const int* xy) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3713:23
(*__claw_result_) = nk_vec2iv(xy);
return __claw_result_;
}

__CLAW_API struct nk_vec2* __claw_nk_vec2i(struct nk_vec2* __claw_result_, int x, int y) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3711:23
(*__claw_result_) = nk_vec2i(x, y);
return __claw_result_;
}

__CLAW_API struct nk_vec2* __claw_nk_vec2(struct nk_vec2* __claw_result_, float x, float y) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3710:23
(*__claw_result_) = nk_vec2(x, y);
return __claw_result_;
}

__CLAW_API void __claw_nk_triangle_from_direction(struct nk_vec2* result, struct nk_rect* r, float pad_x, float pad_y, enum nk_heading arg4) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3708:13
nk_triangle_from_direction(result, *r, pad_x, pad_y, arg4);
}

__CLAW_API int __claw_nk_tree_state_image_push(struct nk_context* arg0, enum nk_tree_type arg1, struct nk_image* arg2, const char* title, enum nk_collapse_states* state) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3001:12
return nk_tree_state_image_push(arg0, arg1, *arg2, title, state);
}

__CLAW_API int __claw_nk_tree_image_push_hashed(struct nk_context* arg0, enum nk_tree_type arg1, struct nk_image* arg2, const char* title, enum nk_collapse_states initial_state, const char* hash, int len, int seed) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:2957:12
return nk_tree_image_push_hashed(arg0, arg1, *arg2, title, initial_state, hash, len, seed);
}

__CLAW_API int __claw_nk_tree_element_image_push_hashed(struct nk_context* arg0, enum nk_tree_type arg1, struct nk_image* arg2, const char* title, enum nk_collapse_states initial_state, int* selected, const char* hash, int len, int seed) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3017:12
return nk_tree_element_image_push_hashed(arg0, arg1, *arg2, title, initial_state, selected, hash, len, seed);
}

__CLAW_API void __claw_cE3AE40FE40nk_text_wrap_colored(struct nk_context* arg0, const char* arg1, int arg2, struct nk_color* arg3) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3088:13
nk_text_wrap_colored(arg0, arg1, arg2, *arg3);
}

__CLAW_API void __claw_cE3AE40FE40nk_text_colored(struct nk_context* arg0, const char* arg1, int arg2, nk_flags arg3, struct nk_color* arg4) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3086:13
nk_text_colored(arg0, arg1, arg2, arg3, *arg4);
}

__CLAW_API struct nk_image* __claw_nk_subimage_ptr(struct nk_image* __claw_result_, void* arg0, unsigned short w, unsigned short h, struct nk_rect* sub_region) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3699:24
(*__claw_result_) = nk_subimage_ptr(arg0, w, h, *sub_region);
return __claw_result_;
}

__CLAW_API struct nk_image* __claw_nk_subimage_id(struct nk_image* __claw_result_, int arg0, unsigned short w, unsigned short h, struct nk_rect* sub_region) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3700:24
(*__claw_result_) = nk_subimage_id(arg0, w, h, *sub_region);
return __claw_result_;
}

__CLAW_API struct nk_image* __claw_nk_subimage_handle(struct nk_image* __claw_result_, nk_handle* arg0, unsigned short w, unsigned short h, struct nk_rect* sub_region) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3701:24
(*__claw_result_) = nk_subimage_handle(*arg0, w, h, *sub_region);
return __claw_result_;
}

__CLAW_API int __claw_cE3AE40FE40nk_style_push_vec2(struct nk_context* arg0, struct nk_vec2* arg1, struct nk_vec2* arg2) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3614:12
return nk_style_push_vec2(arg0, arg1, *arg2);
}

__CLAW_API int __claw_cE3AE40FE40nk_style_push_style_item(struct nk_context* arg0, struct nk_style_item* arg1, struct nk_style_item* arg2) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3615:12
return nk_style_push_style_item(arg0, arg1, *arg2);
}

__CLAW_API int __claw_cE3AE40FE40nk_style_push_color(struct nk_context* arg0, struct nk_color* arg1, struct nk_color* arg2) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3617:12
return nk_style_push_color(arg0, arg1, *arg2);
}

__CLAW_API struct nk_style_item* __claw_nk_style_item_image(struct nk_style_item* __claw_result_, struct nk_image* img) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:5238:29
(*__claw_result_) = nk_style_item_image(*img);
return __claw_result_;
}

__CLAW_API struct nk_style_item* __claw_cE3AE40FE40nk_style_item_hide(struct nk_style_item* __claw_result_) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:5240:29
(*__claw_result_) = nk_style_item_hide();
return __claw_result_;
}

__CLAW_API struct nk_style_item* __claw_cE3AE40FE40nk_style_item_color(struct nk_style_item* __claw_result_, struct nk_color* arg0) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:5239:29
(*__claw_result_) = nk_style_item_color(*arg0);
return __claw_result_;
}

__CLAW_API void __claw_nk_stroke_triangle(struct nk_command_buffer* arg0, float arg1, float arg2, float arg3, float arg4, float arg5, float arg6, float line_thichness, struct nk_color* arg8) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:4576:13
nk_stroke_triangle(arg0, arg1, arg2, arg3, arg4, arg5, arg6, line_thichness, *arg8);
}

__CLAW_API void __claw_nk_stroke_rect(struct nk_command_buffer* arg0, struct nk_rect* arg1, float rounding, float line_thickness, struct nk_color* arg4) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:4573:13
nk_stroke_rect(arg0, *arg1, rounding, line_thickness, *arg4);
}

__CLAW_API void __claw_nk_stroke_polyline(struct nk_command_buffer* arg0, float* points, int point_count, float line_thickness, struct nk_color* col) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:4577:13
nk_stroke_polyline(arg0, points, point_count, line_thickness, *col);
}

__CLAW_API void __claw_nk_stroke_polygon(struct nk_command_buffer* arg0, float* arg1, int point_count, float line_thickness, struct nk_color* arg4) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:4578:13
nk_stroke_polygon(arg0, arg1, point_count, line_thickness, *arg4);
}

__CLAW_API void __claw_nk_stroke_line(struct nk_command_buffer* b, float x0, float y0, float x1, float y1, float line_thickness, struct nk_color* arg6) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:4571:13
nk_stroke_line(b, x0, y0, x1, y1, line_thickness, *arg6);
}

__CLAW_API void __claw_nk_stroke_curve(struct nk_command_buffer* arg0, float arg1, float arg2, float arg3, float arg4, float arg5, float arg6, float arg7, float arg8, float line_thickness, struct nk_color* arg10) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:4572:13
nk_stroke_curve(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, line_thickness, *arg10);
}

__CLAW_API void __claw_nk_stroke_circle(struct nk_command_buffer* arg0, struct nk_rect* arg1, float line_thickness, struct nk_color* arg3) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:4574:13
nk_stroke_circle(arg0, *arg1, line_thickness, *arg3);
}

__CLAW_API void __claw_nk_stroke_arc(struct nk_command_buffer* arg0, float cx, float cy, float radius, float a_min, float a_max, float line_thickness, struct nk_color* arg7) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:4575:13
nk_stroke_arc(arg0, cx, cy, radius, a_min, a_max, line_thickness, *arg7);
}

__CLAW_API int __claw_nk_selectable_image_text(struct nk_context* arg0, struct nk_image* arg1, const char* arg2, int arg3, nk_flags align, int* value) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3167:12
return nk_selectable_image_text(arg0, *arg1, arg2, arg3, align, value);
}

__CLAW_API int __claw_nk_selectable_image_label(struct nk_context* arg0, struct nk_image* arg1, const char* arg2, nk_flags align, int* value) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3166:12
return nk_selectable_image_label(arg0, *arg1, arg2, align, value);
}

__CLAW_API int __claw_nk_select_image_text(struct nk_context* arg0, struct nk_image* arg1, const char* arg2, int arg3, nk_flags align, int value) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3174:12
return nk_select_image_text(arg0, *arg1, arg2, arg3, align, value);
}

__CLAW_API int __claw_nk_select_image_label(struct nk_context* arg0, struct nk_image* arg1, const char* arg2, nk_flags align, int value) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3173:12
return nk_select_image_label(arg0, *arg1, arg2, align, value);
}

__CLAW_API struct nk_color* __claw_cE3AE40FE40nk_rgba_u32(struct nk_color* __claw_result_, nk_uint arg0) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3639:24
(*__claw_result_) = nk_rgba_u32(arg0);
return __claw_result_;
}

__CLAW_API struct nk_color* __claw_nk_rgba_iv(struct nk_color* __claw_result_, const int* rgba) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3640:24
(*__claw_result_) = nk_rgba_iv(rgba);
return __claw_result_;
}

__CLAW_API struct nk_color* __claw_nk_rgba_hex(struct nk_color* __claw_result_, const char* rgb) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3645:24
(*__claw_result_) = nk_rgba_hex(rgb);
return __claw_result_;
}

__CLAW_API struct nk_color* __claw_nk_rgba_fv(struct nk_color* __claw_result_, const float* rgba) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3643:24
(*__claw_result_) = nk_rgba_fv(rgba);
return __claw_result_;
}

__CLAW_API struct nk_color* __claw_nk_rgba_f(struct nk_color* __claw_result_, float r, float g, float b, float a) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3642:24
(*__claw_result_) = nk_rgba_f(r, g, b, a);
return __claw_result_;
}

__CLAW_API struct nk_color* __claw_nk_rgba_cf(struct nk_color* __claw_result_, struct nk_colorf* c) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3644:24
(*__claw_result_) = nk_rgba_cf(*c);
return __claw_result_;
}

__CLAW_API struct nk_color* __claw_nk_rgba_bv(struct nk_color* __claw_result_, const nk_byte* rgba) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3641:24
(*__claw_result_) = nk_rgba_bv(rgba);
return __claw_result_;
}

__CLAW_API struct nk_color* __claw_nk_rgba(struct nk_color* __claw_result_, int r, int g, int b, int a) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3638:24
(*__claw_result_) = nk_rgba(r, g, b, a);
return __claw_result_;
}

__CLAW_API struct nk_color* __claw_nk_rgb_iv(struct nk_color* __claw_result_, const int* rgb) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3631:24
(*__claw_result_) = nk_rgb_iv(rgb);
return __claw_result_;
}

__CLAW_API struct nk_color* __claw_nk_rgb_hex(struct nk_color* __claw_result_, const char* rgb) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3636:24
(*__claw_result_) = nk_rgb_hex(rgb);
return __claw_result_;
}

__CLAW_API struct nk_color* __claw_nk_rgb_fv(struct nk_color* __claw_result_, const float* rgb) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3634:24
(*__claw_result_) = nk_rgb_fv(rgb);
return __claw_result_;
}

__CLAW_API struct nk_color* __claw_nk_rgb_f(struct nk_color* __claw_result_, float r, float g, float b) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3633:24
(*__claw_result_) = nk_rgb_f(r, g, b);
return __claw_result_;
}

__CLAW_API struct nk_color* __claw_nk_rgb_cf(struct nk_color* __claw_result_, struct nk_colorf* c) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3635:24
(*__claw_result_) = nk_rgb_cf(*c);
return __claw_result_;
}

__CLAW_API struct nk_color* __claw_nk_rgb_bv(struct nk_color* __claw_result_, const nk_byte* rgb) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3632:24
(*__claw_result_) = nk_rgb_bv(rgb);
return __claw_result_;
}

__CLAW_API struct nk_color* __claw_nk_rgb(struct nk_color* __claw_result_, int r, int g, int b) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3630:24
(*__claw_result_) = nk_rgb(r, g, b);
return __claw_result_;
}

__CLAW_API struct nk_rect* __claw_nk_rectv(struct nk_rect* __claw_result_, const float* xywh) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3719:23
(*__claw_result_) = nk_rectv(xywh);
return __claw_result_;
}

__CLAW_API struct nk_rect* __claw_nk_rectiv(struct nk_rect* __claw_result_, const int* xywh) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3720:23
(*__claw_result_) = nk_rectiv(xywh);
return __claw_result_;
}

__CLAW_API struct nk_rect* __claw_nk_recti(struct nk_rect* __claw_result_, int x, int y, int w, int h) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3717:23
(*__claw_result_) = nk_recti(x, y, w, h);
return __claw_result_;
}

__CLAW_API struct nk_rect* __claw_nk_recta(struct nk_rect* __claw_result_, struct nk_vec2* pos, struct nk_vec2* size) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3718:23
(*__claw_result_) = nk_recta(*pos, *size);
return __claw_result_;
}

__CLAW_API struct nk_vec2* __claw_cE3AE40FE40nk_rect_size(struct nk_vec2* __claw_result_, struct nk_rect* arg0) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3722:23
(*__claw_result_) = nk_rect_size(*arg0);
return __claw_result_;
}

__CLAW_API struct nk_vec2* __claw_cE3AE40FE40nk_rect_pos(struct nk_vec2* __claw_result_, struct nk_rect* arg0) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3721:23
(*__claw_result_) = nk_rect_pos(*arg0);
return __claw_result_;
}

__CLAW_API struct nk_rect* __claw_nk_rect(struct nk_rect* __claw_result_, float x, float y, float w, float h) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3716:23
(*__claw_result_) = nk_rect(x, y, w, h);
return __claw_result_;
}

__CLAW_API void __claw_cE3AE40FE40nk_push_scissor(struct nk_command_buffer* arg0, struct nk_rect* arg1) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:4591:13
nk_push_scissor(arg0, *arg1);
}

__CLAW_API void __claw_nk_push_custom(struct nk_command_buffer* arg0, struct nk_rect* arg1, nk_command_custom_callback arg2, nk_handle* usr) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:4592:13
nk_push_custom(arg0, *arg1, arg2, *usr);
}

__CLAW_API int __claw_nk_popup_begin(struct nk_context* arg0, enum nk_popup_type arg1, const char* arg2, nk_flags arg3, struct nk_rect* bounds) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3467:12
return nk_popup_begin(arg0, arg1, arg2, arg3, *bounds);
}

__CLAW_API int __claw_nk_menu_item_image_text(struct nk_context* arg0, struct nk_image* arg1, const char* arg2, int len, nk_flags alignment) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3551:12
return nk_menu_item_image_text(arg0, *arg1, arg2, len, alignment);
}

__CLAW_API int __claw_nk_menu_item_image_label(struct nk_context* arg0, struct nk_image* arg1, const char* arg2, nk_flags alignment) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3550:12
return nk_menu_item_image_label(arg0, *arg1, arg2, alignment);
}

__CLAW_API int __claw_nk_menu_begin_text(struct nk_context* arg0, const char* title, int title_len, nk_flags align, struct nk_vec2* size) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3540:12
return nk_menu_begin_text(arg0, title, title_len, align, *size);
}

__CLAW_API int __claw_nk_menu_begin_symbol_text(struct nk_context* arg0, const char* arg1, int arg2, nk_flags align, enum nk_symbol_type arg4, struct nk_vec2* size) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3546:12
return nk_menu_begin_symbol_text(arg0, arg1, arg2, align, arg4, *size);
}

__CLAW_API int __claw_nk_menu_begin_symbol_label(struct nk_context* arg0, const char* arg1, nk_flags align, enum nk_symbol_type arg3, struct nk_vec2* size) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3547:12
return nk_menu_begin_symbol_label(arg0, arg1, align, arg3, *size);
}

__CLAW_API int __claw_nk_menu_begin_symbol(struct nk_context* arg0, const char* arg1, enum nk_symbol_type arg2, struct nk_vec2* size) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3545:12
return nk_menu_begin_symbol(arg0, arg1, arg2, *size);
}

__CLAW_API int __claw_nk_menu_begin_label(struct nk_context* arg0, const char* arg1, nk_flags align, struct nk_vec2* size) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3541:12
return nk_menu_begin_label(arg0, arg1, align, *size);
}

__CLAW_API int __claw_nk_menu_begin_image_text(struct nk_context* arg0, const char* arg1, int arg2, nk_flags align, struct nk_image* arg4, struct nk_vec2* size) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3543:12
return nk_menu_begin_image_text(arg0, arg1, arg2, align, *arg4, *size);
}

__CLAW_API int __claw_nk_menu_begin_image_label(struct nk_context* arg0, const char* arg1, nk_flags align, struct nk_image* arg3, struct nk_vec2* size) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3544:12
return nk_menu_begin_image_label(arg0, arg1, align, *arg3, *size);
}

__CLAW_API int __claw_nk_menu_begin_image(struct nk_context* arg0, const char* arg1, struct nk_image* arg2, struct nk_vec2* size) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3542:12
return nk_menu_begin_image(arg0, arg1, *arg2, *size);
}

__CLAW_API struct nk_rect* __claw_cE3AE40FE40nk_layout_widget_bounds(struct nk_rect* __claw_result_, struct nk_context* arg0) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:2299:23
(*__claw_result_) = nk_layout_widget_bounds(arg0);
return __claw_result_;
}

__CLAW_API struct nk_vec2* __claw_cE3AE40FE40nk_layout_space_to_screen(struct nk_vec2* __claw_result_, struct nk_context* arg0, struct nk_vec2* arg1) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:2518:23
(*__claw_result_) = nk_layout_space_to_screen(arg0, *arg1);
return __claw_result_;
}

__CLAW_API struct nk_vec2* __claw_cE3AE40FE40nk_layout_space_to_local(struct nk_vec2* __claw_result_, struct nk_context* arg0, struct nk_vec2* arg1) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:2532:23
(*__claw_result_) = nk_layout_space_to_local(arg0, *arg1);
return __claw_result_;
}

__CLAW_API struct nk_rect* __claw_cE3AE40FE40nk_layout_space_rect_to_screen(struct nk_rect* __claw_result_, struct nk_context* arg0, struct nk_rect* arg1) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:2546:23
(*__claw_result_) = nk_layout_space_rect_to_screen(arg0, *arg1);
return __claw_result_;
}

__CLAW_API struct nk_rect* __claw_cE3AE40FE40nk_layout_space_rect_to_local(struct nk_rect* __claw_result_, struct nk_context* arg0, struct nk_rect* arg1) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:2560:23
(*__claw_result_) = nk_layout_space_rect_to_local(arg0, *arg1);
return __claw_result_;
}

__CLAW_API void __claw_nk_layout_space_push(struct nk_context* arg0, struct nk_rect* bounds) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:2480:13
nk_layout_space_push(arg0, *bounds);
}

__CLAW_API struct nk_rect* __claw_cE3AE40FE40nk_layout_space_bounds(struct nk_rect* __claw_result_, struct nk_context* arg0) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:2504:23
(*__claw_result_) = nk_layout_space_bounds(arg0);
return __claw_result_;
}

__CLAW_API void __claw_cE3AE40FE40nk_label_colored_wrap(struct nk_context* arg0, const char* arg1, struct nk_color* arg2) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3092:13
nk_label_colored_wrap(arg0, arg1, *arg2);
}

__CLAW_API void __claw_nk_label_colored(struct nk_context* arg0, const char* arg1, nk_flags align, struct nk_color* arg3) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3090:13
nk_label_colored(arg0, arg1, align, *arg3);
}

__CLAW_API void __claw_nk_input_scroll(struct nk_context* arg0, struct nk_vec2* val) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:848:13
nk_input_scroll(arg0, *val);
}

__CLAW_API int __claw_cE3AE40FE40nk_input_mouse_clicked(const struct nk_input* arg0, enum nk_buttons arg1, struct nk_rect* arg2) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:4638:12
return nk_input_mouse_clicked(arg0, arg1, *arg2);
}

__CLAW_API int __claw_cE3AE40FE40nk_input_is_mouse_prev_hovering_rect(const struct nk_input* arg0, struct nk_rect* arg1) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:4636:12
return nk_input_is_mouse_prev_hovering_rect(arg0, *arg1);
}

__CLAW_API int __claw_cE3AE40FE40nk_input_is_mouse_hovering_rect(const struct nk_input* arg0, struct nk_rect* arg1) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:4637:12
return nk_input_is_mouse_hovering_rect(arg0, *arg1);
}

__CLAW_API int __claw_cE3AE40FE40nk_input_is_mouse_click_in_rect(const struct nk_input* arg0, enum nk_buttons arg1, struct nk_rect* arg2) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:4633:12
return nk_input_is_mouse_click_in_rect(arg0, arg1, *arg2);
}

__CLAW_API int __claw_nk_input_is_mouse_click_down_in_rect(const struct nk_input* i, enum nk_buttons id, struct nk_rect* b, int down) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:4634:12
return nk_input_is_mouse_click_down_in_rect(i, id, *b, down);
}

__CLAW_API int __claw_cE3AE40FE40nk_input_has_mouse_click_in_rect(const struct nk_input* arg0, enum nk_buttons arg1, struct nk_rect* arg2) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:4631:12
return nk_input_has_mouse_click_in_rect(arg0, arg1, *arg2);
}

__CLAW_API int __claw_nk_input_has_mouse_click_down_in_rect(const struct nk_input* arg0, enum nk_buttons arg1, struct nk_rect* arg2, int down) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:4632:12
return nk_input_has_mouse_click_down_in_rect(arg0, arg1, *arg2, down);
}

__CLAW_API int __claw_cE3AE40FE40nk_input_any_mouse_click_in_rect(const struct nk_input* arg0, struct nk_rect* arg1) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:4635:12
return nk_input_any_mouse_click_in_rect(arg0, *arg1);
}

__CLAW_API struct nk_image* __claw_cE3AE40FE40nk_image_ptr(struct nk_image* __claw_result_, void* arg0) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3696:24
(*__claw_result_) = nk_image_ptr(arg0);
return __claw_result_;
}

__CLAW_API struct nk_image* __claw_cE3AE40FE40nk_image_id(struct nk_image* __claw_result_, int arg0) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3697:24
(*__claw_result_) = nk_image_id(arg0);
return __claw_result_;
}

__CLAW_API struct nk_image* __claw_cE3AE40FE40nk_image_handle(struct nk_image* __claw_result_, nk_handle* arg0) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3695:24
(*__claw_result_) = nk_image_handle(*arg0);
return __claw_result_;
}

__CLAW_API void __claw_cE3AE40FE40nk_image_color(struct nk_context* arg0, struct nk_image* arg1, struct nk_color* arg2) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3094:13
nk_image_color(arg0, *arg1, *arg2);
}

__CLAW_API void __claw_cE3AE40FE40nk_image(struct nk_context* arg0, struct nk_image* arg1) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3093:13
nk_image(arg0, *arg1);
}

__CLAW_API struct nk_color* __claw_nk_hsva_iv(struct nk_color* __claw_result_, const int* hsva) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3659:24
(*__claw_result_) = nk_hsva_iv(hsva);
return __claw_result_;
}

__CLAW_API struct nk_color* __claw_nk_hsva_fv(struct nk_color* __claw_result_, const float* hsva) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3662:24
(*__claw_result_) = nk_hsva_fv(hsva);
return __claw_result_;
}

__CLAW_API struct nk_color* __claw_nk_hsva_f(struct nk_color* __claw_result_, float h, float s, float v, float a) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3661:24
(*__claw_result_) = nk_hsva_f(h, s, v, a);
return __claw_result_;
}

__CLAW_API struct nk_colorf* __claw_nk_hsva_colorfv(struct nk_colorf* __claw_result_, float* c) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3648:25
(*__claw_result_) = nk_hsva_colorfv(c);
return __claw_result_;
}

__CLAW_API struct nk_colorf* __claw_nk_hsva_colorf(struct nk_colorf* __claw_result_, float h, float s, float v, float a) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3647:25
(*__claw_result_) = nk_hsva_colorf(h, s, v, a);
return __claw_result_;
}

__CLAW_API struct nk_color* __claw_nk_hsva_bv(struct nk_color* __claw_result_, const nk_byte* hsva) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3660:24
(*__claw_result_) = nk_hsva_bv(hsva);
return __claw_result_;
}

__CLAW_API struct nk_color* __claw_nk_hsva(struct nk_color* __claw_result_, int h, int s, int v, int a) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3658:24
(*__claw_result_) = nk_hsva(h, s, v, a);
return __claw_result_;
}

__CLAW_API struct nk_color* __claw_nk_hsv_iv(struct nk_color* __claw_result_, const int* hsv) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3653:24
(*__claw_result_) = nk_hsv_iv(hsv);
return __claw_result_;
}

__CLAW_API struct nk_color* __claw_nk_hsv_fv(struct nk_color* __claw_result_, const float* hsv) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3656:24
(*__claw_result_) = nk_hsv_fv(hsv);
return __claw_result_;
}

__CLAW_API struct nk_color* __claw_nk_hsv_f(struct nk_color* __claw_result_, float h, float s, float v) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3655:24
(*__claw_result_) = nk_hsv_f(h, s, v);
return __claw_result_;
}

__CLAW_API struct nk_color* __claw_nk_hsv_bv(struct nk_color* __claw_result_, const nk_byte* hsv) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3654:24
(*__claw_result_) = nk_hsv_bv(hsv);
return __claw_result_;
}

__CLAW_API struct nk_color* __claw_nk_hsv(struct nk_color* __claw_result_, int h, int s, int v) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3652:24
(*__claw_result_) = nk_hsv(h, s, v);
return __claw_result_;
}

__CLAW_API nk_handle* __claw_cE3AE40FE40nk_handle_ptr(nk_handle* __claw_result_, void* arg0) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3693:18
(*__claw_result_) = nk_handle_ptr(arg0);
return __claw_result_;
}

__CLAW_API nk_handle* __claw_cE3AE40FE40nk_handle_id(nk_handle* __claw_result_, int arg0) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3694:18
(*__claw_result_) = nk_handle_id(arg0);
return __claw_result_;
}

__CLAW_API struct nk_rect* __claw_cE3AE40FE40nk_get_null_rect(struct nk_rect* __claw_result_) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3715:23
(*__claw_result_) = nk_get_null_rect();
return __claw_result_;
}

__CLAW_API struct nk_font_config* __claw_nk_font_config(struct nk_font_config* __claw_result_, float pixel_height) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:4040:30
(*__claw_result_) = nk_font_config(pixel_height);
return __claw_result_;
}

__CLAW_API void __claw_nk_font_atlas_end(struct nk_font_atlas* arg0, nk_handle* tex, struct nk_draw_null_texture* arg2) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:4052:13
nk_font_atlas_end(arg0, *tex, arg2);
}

__CLAW_API void __claw_nk_fill_triangle(struct nk_command_buffer* arg0, float x0, float y0, float x1, float y1, float x2, float y2, struct nk_color* arg7) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:4585:13
nk_fill_triangle(arg0, x0, y0, x1, y1, x2, y2, *arg7);
}

__CLAW_API void __claw_nk_fill_rect_multi_color(struct nk_command_buffer* arg0, struct nk_rect* arg1, struct nk_color* left, struct nk_color* top, struct nk_color* right, struct nk_color* bottom) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:4582:13
nk_fill_rect_multi_color(arg0, *arg1, *left, *top, *right, *bottom);
}

__CLAW_API void __claw_nk_fill_rect(struct nk_command_buffer* arg0, struct nk_rect* arg1, float rounding, struct nk_color* arg3) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:4581:13
nk_fill_rect(arg0, *arg1, rounding, *arg3);
}

__CLAW_API void __claw_nk_fill_polygon(struct nk_command_buffer* arg0, float* arg1, int point_count, struct nk_color* arg3) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:4586:13
nk_fill_polygon(arg0, arg1, point_count, *arg3);
}

__CLAW_API void __claw_cE3AE40FE40nk_fill_circle(struct nk_command_buffer* arg0, struct nk_rect* arg1, struct nk_color* arg2) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:4583:13
nk_fill_circle(arg0, *arg1, *arg2);
}

__CLAW_API void __claw_nk_fill_arc(struct nk_command_buffer* arg0, float cx, float cy, float radius, float a_min, float a_max, struct nk_color* arg6) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:4584:13
nk_fill_arc(arg0, cx, cy, radius, a_min, a_max, *arg6);
}

__CLAW_API void __claw_nk_draw_text(struct nk_command_buffer* arg0, struct nk_rect* arg1, const char* text, int len, const struct nk_user_font* arg4, struct nk_color* arg5, struct nk_color* arg6) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:4590:13
nk_draw_text(arg0, *arg1, text, len, arg4, *arg5, *arg6);
}

__CLAW_API void __claw_nk_draw_list_stroke_triangle(struct nk_draw_list* arg0, struct nk_vec2* a, struct nk_vec2* b, struct nk_vec2* c, struct nk_color* arg4, float thickness) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:4779:13
nk_draw_list_stroke_triangle(arg0, *a, *b, *c, *arg4, thickness);
}

__CLAW_API void __claw_nk_draw_list_stroke_rect(struct nk_draw_list* arg0, struct nk_rect* rect, struct nk_color* arg2, float rounding, float thickness) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:4778:13
nk_draw_list_stroke_rect(arg0, *rect, *arg2, rounding, thickness);
}

__CLAW_API void __claw_nk_draw_list_stroke_poly_line(struct nk_draw_list* arg0, const struct nk_vec2* pnts, const unsigned int cnt, struct nk_color* arg3, enum nk_draw_list_stroke arg4, float thickness, enum nk_anti_aliasing arg6) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:4782:13
nk_draw_list_stroke_poly_line(arg0, pnts, cnt, *arg3, arg4, thickness, arg6);
}

__CLAW_API void __claw_nk_draw_list_stroke_line(struct nk_draw_list* arg0, struct nk_vec2* a, struct nk_vec2* b, struct nk_color* arg3, float thickness) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:4777:13
nk_draw_list_stroke_line(arg0, *a, *b, *arg3, thickness);
}

__CLAW_API void __claw_nk_draw_list_stroke_curve(struct nk_draw_list* arg0, struct nk_vec2* p0, struct nk_vec2* cp0, struct nk_vec2* cp1, struct nk_vec2* p1, struct nk_color* arg5, unsigned int segments, float thickness) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:4781:13
nk_draw_list_stroke_curve(arg0, *p0, *cp0, *cp1, *p1, *arg5, segments, thickness);
}

__CLAW_API void __claw_nk_draw_list_stroke_circle(struct nk_draw_list* arg0, struct nk_vec2* center, float radius, struct nk_color* arg3, unsigned int segs, float thickness) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:4780:13
nk_draw_list_stroke_circle(arg0, *center, radius, *arg3, segs, thickness);
}

__CLAW_API void __claw_nk_draw_list_path_stroke(struct nk_draw_list* arg0, struct nk_color* arg1, enum nk_draw_list_stroke closed, float thickness) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:4774:13
nk_draw_list_path_stroke(arg0, *arg1, closed, thickness);
}

__CLAW_API void __claw_nk_draw_list_path_rect_to(struct nk_draw_list* arg0, struct nk_vec2* a, struct nk_vec2* b, float rounding) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:4771:13
nk_draw_list_path_rect_to(arg0, *a, *b, rounding);
}

__CLAW_API void __claw_nk_draw_list_path_line_to(struct nk_draw_list* arg0, struct nk_vec2* pos) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:4768:13
nk_draw_list_path_line_to(arg0, *pos);
}

__CLAW_API void __claw_cE3AE40FE40nk_draw_list_path_fill(struct nk_draw_list* arg0, struct nk_color* arg1) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:4773:13
nk_draw_list_path_fill(arg0, *arg1);
}

__CLAW_API void __claw_nk_draw_list_path_curve_to(struct nk_draw_list* arg0, struct nk_vec2* p2, struct nk_vec2* p3, struct nk_vec2* p4, unsigned int num_segments) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:4772:13
nk_draw_list_path_curve_to(arg0, *p2, *p3, *p4, num_segments);
}

__CLAW_API void __claw_nk_draw_list_path_arc_to_fast(struct nk_draw_list* arg0, struct nk_vec2* center, float radius, int a_min, int a_max) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:4769:13
nk_draw_list_path_arc_to_fast(arg0, *center, radius, a_min, a_max);
}

__CLAW_API void __claw_nk_draw_list_path_arc_to(struct nk_draw_list* arg0, struct nk_vec2* center, float radius, float a_min, float a_max, unsigned int segments) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:4770:13
nk_draw_list_path_arc_to(arg0, *center, radius, a_min, a_max, segments);
}

__CLAW_API void __claw_nk_draw_list_fill_triangle(struct nk_draw_list* arg0, struct nk_vec2* a, struct nk_vec2* b, struct nk_vec2* c, struct nk_color* arg4) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:4787:13
nk_draw_list_fill_triangle(arg0, *a, *b, *c, *arg4);
}

__CLAW_API void __claw_nk_draw_list_fill_rect_multi_color(struct nk_draw_list* arg0, struct nk_rect* rect, struct nk_color* left, struct nk_color* top, struct nk_color* right, struct nk_color* bottom) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:4786:13
nk_draw_list_fill_rect_multi_color(arg0, *rect, *left, *top, *right, *bottom);
}

__CLAW_API void __claw_nk_draw_list_fill_rect(struct nk_draw_list* arg0, struct nk_rect* rect, struct nk_color* arg2, float rounding) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:4785:13
nk_draw_list_fill_rect(arg0, *rect, *arg2, rounding);
}

__CLAW_API void __claw_nk_draw_list_fill_poly_convex(struct nk_draw_list* arg0, const struct nk_vec2* points, const unsigned int count, struct nk_color* arg3, enum nk_anti_aliasing arg4) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:4789:13
nk_draw_list_fill_poly_convex(arg0, points, count, *arg3, arg4);
}

__CLAW_API void __claw_nk_draw_list_fill_circle(struct nk_draw_list* arg0, struct nk_vec2* center, float radius, struct nk_color* col, unsigned int segs) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:4788:13
nk_draw_list_fill_circle(arg0, *center, radius, *col, segs);
}

__CLAW_API void __claw_nk_draw_list_add_text(struct nk_draw_list* arg0, const struct nk_user_font* arg1, struct nk_rect* arg2, const char* text, int len, float font_height, struct nk_color* arg6) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:4793:13
nk_draw_list_add_text(arg0, arg1, *arg2, text, len, font_height, *arg6);
}

__CLAW_API void __claw_nk_draw_list_add_image(struct nk_draw_list* arg0, struct nk_image* texture, struct nk_rect* rect, struct nk_color* arg3) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:4792:13
nk_draw_list_add_image(arg0, *texture, *rect, *arg3);
}

__CLAW_API void __claw_cE3AE40FE40nk_draw_image(struct nk_command_buffer* arg0, struct nk_rect* arg1, const struct nk_image* arg2, struct nk_color* arg3) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:4589:13
nk_draw_image(arg0, *arg1, arg2, *arg3);
}

__CLAW_API int __claw_nk_contextual_item_image_text(struct nk_context* arg0, struct nk_image* arg1, const char* arg2, int len, nk_flags alignment) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3516:12
return nk_contextual_item_image_text(arg0, *arg1, arg2, len, alignment);
}

__CLAW_API int __claw_nk_contextual_item_image_label(struct nk_context* arg0, struct nk_image* arg1, const char* arg2, nk_flags alignment) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3515:12
return nk_contextual_item_image_label(arg0, *arg1, arg2, alignment);
}

__CLAW_API int __claw_nk_contextual_begin(struct nk_context* arg0, nk_flags arg1, struct nk_vec2* arg2, struct nk_rect* trigger_bounds) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3512:12
return nk_contextual_begin(arg0, arg1, *arg2, *trigger_bounds);
}

__CLAW_API void __claw_nk_combobox_string(struct nk_context* arg0, const char* items_separated_by_zeros, int* selected, int count, int item_height, struct nk_vec2* size) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3482:13
nk_combobox_string(arg0, items_separated_by_zeros, selected, count, item_height, *size);
}

__CLAW_API void __claw_nk_combobox_separator(struct nk_context* arg0, const char* items_separated_by_separator, int separator, int* selected, int count, int item_height, struct nk_vec2* size) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3483:13
nk_combobox_separator(arg0, items_separated_by_separator, separator, selected, count, item_height, *size);
}

__CLAW_API void __claw_nk_combobox_callback(struct nk_context* arg0, void(*item_getter)(void*, int, const char**), void* arg2, int* selected, int count, int item_height, struct nk_vec2* size) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3484:13
nk_combobox_callback(arg0, item_getter, arg2, selected, count, item_height, *size);
}

__CLAW_API void __claw_nk_combobox(struct nk_context* arg0, const char** items, int count, int* selected, int item_height, struct nk_vec2* size) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3481:13
nk_combobox(arg0, items, count, selected, item_height, *size);
}

__CLAW_API int __claw_nk_combo_string(struct nk_context* arg0, const char* items_separated_by_zeros, int selected, int count, int item_height, struct nk_vec2* size) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3479:12
return nk_combo_string(arg0, items_separated_by_zeros, selected, count, item_height, *size);
}

__CLAW_API int __claw_nk_combo_separator(struct nk_context* arg0, const char* items_separated_by_separator, int separator, int selected, int count, int item_height, struct nk_vec2* size) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3478:12
return nk_combo_separator(arg0, items_separated_by_separator, separator, selected, count, item_height, *size);
}

__CLAW_API int __claw_nk_combo_item_image_text(struct nk_context* arg0, struct nk_image* arg1, const char* arg2, int arg3, nk_flags alignment) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3502:12
return nk_combo_item_image_text(arg0, *arg1, arg2, arg3, alignment);
}

__CLAW_API int __claw_nk_combo_item_image_label(struct nk_context* arg0, struct nk_image* arg1, const char* arg2, nk_flags alignment) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3501:12
return nk_combo_item_image_label(arg0, *arg1, arg2, alignment);
}

__CLAW_API int __claw_nk_combo_callback(struct nk_context* arg0, void(*item_getter)(void*, int, const char**), void* userdata, int selected, int count, int item_height, struct nk_vec2* size) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3480:12
return nk_combo_callback(arg0, item_getter, userdata, selected, count, item_height, *size);
}

__CLAW_API int __claw_nk_combo_begin_text(struct nk_context* arg0, const char* selected, int arg2, struct nk_vec2* size) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3490:12
return nk_combo_begin_text(arg0, selected, arg2, *size);
}

__CLAW_API int __claw_nk_combo_begin_symbol_text(struct nk_context* arg0, const char* selected, int arg2, enum nk_symbol_type arg3, struct nk_vec2* size) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3495:12
return nk_combo_begin_symbol_text(arg0, selected, arg2, arg3, *size);
}

__CLAW_API int __claw_nk_combo_begin_symbol_label(struct nk_context* arg0, const char* selected, enum nk_symbol_type arg2, struct nk_vec2* size) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3494:12
return nk_combo_begin_symbol_label(arg0, selected, arg2, *size);
}

__CLAW_API int __claw_nk_combo_begin_symbol(struct nk_context* arg0, enum nk_symbol_type arg1, struct nk_vec2* size) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3493:12
return nk_combo_begin_symbol(arg0, arg1, *size);
}

__CLAW_API int __claw_nk_combo_begin_label(struct nk_context* arg0, const char* selected, struct nk_vec2* size) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3491:12
return nk_combo_begin_label(arg0, selected, *size);
}

__CLAW_API int __claw_nk_combo_begin_image_text(struct nk_context* arg0, const char* selected, int arg2, struct nk_image* arg3, struct nk_vec2* size) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3498:12
return nk_combo_begin_image_text(arg0, selected, arg2, *arg3, *size);
}

__CLAW_API int __claw_nk_combo_begin_image_label(struct nk_context* arg0, const char* selected, struct nk_image* arg2, struct nk_vec2* size) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3497:12
return nk_combo_begin_image_label(arg0, selected, *arg2, *size);
}

__CLAW_API int __claw_nk_combo_begin_image(struct nk_context* arg0, struct nk_image* img, struct nk_vec2* size) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3496:12
return nk_combo_begin_image(arg0, *img, *size);
}

__CLAW_API int __claw_nk_combo_begin_color(struct nk_context* arg0, struct nk_color* color, struct nk_vec2* size) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3492:12
return nk_combo_begin_color(arg0, *color, *size);
}

__CLAW_API int __claw_nk_combo(struct nk_context* arg0, const char** items, int count, int selected, int item_height, struct nk_vec2* size) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3477:12
return nk_combo(arg0, items, count, selected, item_height, *size);
}

__CLAW_API void __claw_nk_colorf_hsva_fv(float* hsva, struct nk_colorf* in) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3650:13
nk_colorf_hsva_fv(hsva, *in);
}

__CLAW_API void __claw_nk_colorf_hsva_f(float* out_h, float* out_s, float* out_v, float* out_a, struct nk_colorf* in) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3649:13
nk_colorf_hsva_f(out_h, out_s, out_v, out_a, *in);
}

__CLAW_API nk_uint __claw_cE3AE40FE40nk_color_u32(struct nk_color* arg0) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3671:16
return nk_color_u32(*arg0);
}

__CLAW_API struct nk_colorf* __claw_cE3AE40FE40nk_color_picker(struct nk_colorf* __claw_result_, struct nk_context* arg0, struct nk_colorf* arg1, enum nk_color_format arg2) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3200:25
(*__claw_result_) = nk_color_picker(arg0, *arg1, arg2);
return __claw_result_;
}

__CLAW_API void __claw_nk_color_hsva_iv(int* hsva_out, struct nk_color* arg1) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3684:13
nk_color_hsva_iv(hsva_out, *arg1);
}

__CLAW_API void __claw_nk_color_hsva_i(int* h, int* s, int* v, int* a, struct nk_color* arg4) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3682:13
nk_color_hsva_i(h, s, v, a, *arg4);
}

__CLAW_API void __claw_nk_color_hsva_fv(float* hsva_out, struct nk_color* arg1) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3687:13
nk_color_hsva_fv(hsva_out, *arg1);
}

__CLAW_API void __claw_nk_color_hsva_f(float* out_h, float* out_s, float* out_v, float* out_a, struct nk_color* arg4) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3686:13
nk_color_hsva_f(out_h, out_s, out_v, out_a, *arg4);
}

__CLAW_API void __claw_nk_color_hsva_bv(nk_byte* hsva_out, struct nk_color* arg1) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3685:13
nk_color_hsva_bv(hsva_out, *arg1);
}

__CLAW_API void __claw_nk_color_hsva_b(nk_byte* h, nk_byte* s, nk_byte* v, nk_byte* a, struct nk_color* arg4) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3683:13
nk_color_hsva_b(h, s, v, a, *arg4);
}

__CLAW_API void __claw_nk_color_hsv_iv(int* hsv_out, struct nk_color* arg1) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3677:13
nk_color_hsv_iv(hsv_out, *arg1);
}

__CLAW_API void __claw_nk_color_hsv_i(int* out_h, int* out_s, int* out_v, struct nk_color* arg3) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3675:13
nk_color_hsv_i(out_h, out_s, out_v, *arg3);
}

__CLAW_API void __claw_nk_color_hsv_fv(float* hsv_out, struct nk_color* arg1) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3680:13
nk_color_hsv_fv(hsv_out, *arg1);
}

__CLAW_API void __claw_nk_color_hsv_f(float* out_h, float* out_s, float* out_v, struct nk_color* arg3) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3679:13
nk_color_hsv_f(out_h, out_s, out_v, *arg3);
}

__CLAW_API void __claw_nk_color_hsv_bv(nk_byte* hsv_out, struct nk_color* arg1) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3678:13
nk_color_hsv_bv(hsv_out, *arg1);
}

__CLAW_API void __claw_nk_color_hsv_b(nk_byte* out_h, nk_byte* out_s, nk_byte* out_v, struct nk_color* arg3) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3676:13
nk_color_hsv_b(out_h, out_s, out_v, *arg3);
}

__CLAW_API void __claw_nk_color_hex_rgba(char* output, struct nk_color* arg1) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3672:13
nk_color_hex_rgba(output, *arg1);
}

__CLAW_API void __claw_nk_color_hex_rgb(char* output, struct nk_color* arg1) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3673:13
nk_color_hex_rgb(output, *arg1);
}

__CLAW_API void __claw_nk_color_fv(float* rgba_out, struct nk_color* arg1) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3666:13
nk_color_fv(rgba_out, *arg1);
}

__CLAW_API void __claw_nk_color_f(float* r, float* g, float* b, float* a, struct nk_color* arg4) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3665:13
nk_color_f(r, g, b, a, *arg4);
}

__CLAW_API void __claw_nk_color_dv(double* rgba_out, struct nk_color* arg1) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3669:13
nk_color_dv(rgba_out, *arg1);
}

__CLAW_API void __claw_nk_color_d(double* r, double* g, double* b, double* a, struct nk_color* arg4) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3668:13
nk_color_d(r, g, b, a, *arg4);
}

__CLAW_API struct nk_colorf* __claw_cE3AE40FE40nk_color_cf(struct nk_colorf* __claw_result_, struct nk_color* arg0) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3667:25
(*__claw_result_) = nk_color_cf(*arg0);
return __claw_result_;
}

__CLAW_API int __claw_nk_chart_begin_colored(struct nk_context* arg0, enum nk_chart_type arg1, struct nk_color* arg2, struct nk_color* active, int num, float min, float max) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3454:12
return nk_chart_begin_colored(arg0, arg1, *arg2, *active, num, min, max);
}

__CLAW_API void __claw_nk_chart_add_slot_colored(struct nk_context* ctx, enum nk_chart_type arg1, struct nk_color* arg2, struct nk_color* active, int count, float min_value, float max_value) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3456:13
nk_chart_add_slot_colored(ctx, arg1, *arg2, *active, count, min_value, max_value);
}

__CLAW_API int __claw_nk_button_image_text_styled(struct nk_context* arg0, const struct nk_style_button* arg1, struct nk_image* img, const char* arg3, int arg4, nk_flags alignment) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3133:12
return nk_button_image_text_styled(arg0, arg1, *img, arg3, arg4, alignment);
}

__CLAW_API int __claw_nk_button_image_text(struct nk_context* arg0, struct nk_image* img, const char* arg2, int arg3, nk_flags alignment) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3125:12
return nk_button_image_text(arg0, *img, arg2, arg3, alignment);
}

__CLAW_API int __claw_nk_button_image_styled(struct nk_context* arg0, const struct nk_style_button* arg1, struct nk_image* img) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3129:12
return nk_button_image_styled(arg0, arg1, *img);
}

__CLAW_API int __claw_nk_button_image_label_styled(struct nk_context* arg0, const struct nk_style_button* arg1, struct nk_image* img, const char* arg3, nk_flags text_alignment) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3132:12
return nk_button_image_label_styled(arg0, arg1, *img, arg3, text_alignment);
}

__CLAW_API int __claw_nk_button_image_label(struct nk_context* arg0, struct nk_image* img, const char* arg2, nk_flags text_alignment) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3124:12
return nk_button_image_label(arg0, *img, arg2, text_alignment);
}

__CLAW_API int __claw_nk_button_image(struct nk_context* arg0, struct nk_image* img) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3121:12
return nk_button_image(arg0, *img);
}

__CLAW_API int __claw_cE3AE40FE40nk_button_color(struct nk_context* arg0, struct nk_color* arg1) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:3119:12
return nk_button_color(arg0, *arg1);
}

__CLAW_API int __claw_nk_begin_titled(struct nk_context* ctx, const char* name, const char* title, struct nk_rect* bounds, nk_flags flags) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:1501:12
return nk_begin_titled(ctx, name, title, *bounds, flags);
}

__CLAW_API int __claw_nk_begin(struct nk_context* ctx, const char* title, struct nk_rect* bounds, nk_flags flags) {
// /home/borodust/devel/repo/bodge-projects/bodge-nuklear/src/lib/nuklear/nuklear.h:1481:12
return nk_begin(ctx, title, *bounds, flags);
}

#if defined(__cplusplus)
}
#endif
